Repository MicrosoftDocs/powerShell-Docs.ja-jp, pull requests merged in 2019-07, with the labels that each got.

#17 Fixed a missing link
  reference/docs-conceptual/install/Installing-PowerShell-Core-on-Windows.md
Labels: Accepted, Source Issue

#21 fix "次の文字。 #40 です。 , "→"次の文字: # . , "
  developer/cmdlet/writing-a-windows-powershell-snap-in.md
Labels: Accepted

#22 Typo "(String[]"→"(String[]) "
  developer/cmdlet/alias-attribute-declaration.md
Labels: Accepted, Linguistic Suggestion

#23 [LOC] Back-Translation "形式 (f)"→"Format (f)"
  developer/cmdlet/approved-verbs-for-windows-powershell-commands.md
Labels: Accepted, Linguistic Suggestion
